language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

env:
  - DB=sqlite
  - DB=mysql
  # - DB=postgresql
  - DB=pg

script:
  - rake db:migrate
  - rake test

gemfile:
  - Gemfile
  - gemfiles/Gemfile.sequel-4.9.x
  - gemfiles/Gemfile.sequel-4.8.x
  - gemfiles/Gemfile.sequel-4.7.x
  - gemfiles/Gemfile.sequel-4.6.x
  - gemfiles/Gemfile.sequel-4.5.x
  - gemfiles/Gemfile.sequel-4.4.x
  - gemfiles/Gemfile.sequel-4.3.x
  - gemfiles/Gemfile.sequel-4.2.x
  - gemfiles/Gemfile.sequel-4.27.x
  - gemfiles/Gemfile.sequel-4.26.x
  - gemfiles/Gemfile.sequel-4.25.x
  - gemfiles/Gemfile.sequel-4.24.x
  - gemfiles/Gemfile.sequel-4.23.x
  - gemfiles/Gemfile.sequel-4.22.x
  - gemfiles/Gemfile.sequel-4.21.x
  - gemfiles/Gemfile.sequel-4.20.x
  - gemfiles/Gemfile.sequel-4.1.x
  - gemfiles/Gemfile.sequel-4.19.x
  - gemfiles/Gemfile.sequel-4.18.x
  - gemfiles/Gemfile.sequel-4.17.x
  - gemfiles/Gemfile.sequel-4.16.x
  - gemfiles/Gemfile.sequel-4.15.x
  - gemfiles/Gemfile.sequel-4.14.x
  - gemfiles/Gemfile.sequel-4.13.x
  - gemfiles/Gemfile.sequel-4.12.x
  - gemfiles/Gemfile.sequel-4.11.x
  - gemfiles/Gemfile.sequel-4.10.x
  - gemfiles/Gemfile.sequel-4.0.x
  - gemfiles/Gemfile.sequel-3.9.x
  - gemfiles/Gemfile.sequel-3.8.x
  - gemfiles/Gemfile.sequel-3.7.x
  - gemfiles/Gemfile.sequel-3.6.x
  - gemfiles/Gemfile.sequel-3.5.x
  - gemfiles/Gemfile.sequel-3.4.x
  - gemfiles/Gemfile.sequel-3.48.x
  - gemfiles/Gemfile.sequel-3.47.x
  - gemfiles/Gemfile.sequel-3.46.x
  - gemfiles/Gemfile.sequel-3.45.x
  - gemfiles/Gemfile.sequel-3.44.x
  - gemfiles/Gemfile.sequel-3.43.x
  - gemfiles/Gemfile.sequel-3.42.x
  - gemfiles/Gemfile.sequel-3.41.x
  - gemfiles/Gemfile.sequel-3.40.x
  - gemfiles/Gemfile.sequel-3.3.x
  - gemfiles/Gemfile.sequel-3.39.x
  - gemfiles/Gemfile.sequel-3.38.x
  - gemfiles/Gemfile.sequel-3.37.x
  - gemfiles/Gemfile.sequel-3.36.x
  - gemfiles/Gemfile.sequel-3.35.x
  - gemfiles/Gemfile.sequel-3.34.x
  - gemfiles/Gemfile.sequel-3.33.x
  - gemfiles/Gemfile.sequel-3.32.x
  - gemfiles/Gemfile.sequel-3.31.x
  - gemfiles/Gemfile.sequel-3.30.x
  - gemfiles/Gemfile.sequel-3.2.x
  - gemfiles/Gemfile.sequel-3.29.x
  - gemfiles/Gemfile.sequel-3.28.x
  - gemfiles/Gemfile.sequel-3.27.x
  - gemfiles/Gemfile.sequel-3.26.x
  - gemfiles/Gemfile.sequel-3.25.x
  - gemfiles/Gemfile.sequel-3.24.x
  - gemfiles/Gemfile.sequel-3.23.x
  - gemfiles/Gemfile.sequel-3.22.x
  - gemfiles/Gemfile.sequel-3.21.x
  - gemfiles/Gemfile.sequel-3.20.x
  - gemfiles/Gemfile.sequel-3.1.x
  - gemfiles/Gemfile.sequel-3.19.x
  - gemfiles/Gemfile.sequel-3.18.x
  - gemfiles/Gemfile.sequel-3.17.x
  - gemfiles/Gemfile.sequel-3.16.x
  - gemfiles/Gemfile.sequel-3.15.x
  - gemfiles/Gemfile.sequel-3.14.x
  - gemfiles/Gemfile.sequel-3.13.x
  - gemfiles/Gemfile.sequel-3.12.x
  - gemfiles/Gemfile.sequel-3.11.x
  - gemfiles/Gemfile.sequel-3.10.x
  - gemfiles/Gemfile.sequel-3.0.x
  - gemfiles/Gemfile.sequel-2.9.x
  - gemfiles/Gemfile.sequel-2.8.x
  - gemfiles/Gemfile.sequel-2.7.x
  - gemfiles/Gemfile.sequel-2.6.x
  - gemfiles/Gemfile.sequel-2.5.x
  - gemfiles/Gemfile.sequel-2.4.x
  - gemfiles/Gemfile.sequel-2.3.x
  - gemfiles/Gemfile.sequel-2.2.x
  - gemfiles/Gemfile.sequel-2.1.x
  - gemfiles/Gemfile.sequel-2.12.x
  - gemfiles/Gemfile.sequel-2.11.x
  - gemfiles/Gemfile.sequel-2.10.x
  - gemfiles/Gemfile.sequel-2.0.x
  - gemfiles/Gemfile.sequel-1.5.x
  - gemfiles/Gemfile.sequel-1.4.x
  - gemfiles/Gemfile.sequel-1.3.x
  - gemfiles/Gemfile.sequel-1.2.x
  - gemfiles/Gemfile.sequel-1.1.x
  - gemfiles/Gemfile.sequel-1.0.x


before_script:
  - mysql -e 'create database koine_repository'
  - psql -c 'create database koine_repository' -U postgres

sudo: false
