language: ruby
sudo: false
cache: bundle
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
env:
  - DB=sqlite
  - DB=mysql
  # - DB=postgresql
  - DB=pg
script:
  - rake db:migrate
  - rake test

gemfile:
  - Gemfile
  - gemfiles/Gemfile.sequel-4.27.x
  - gemfiles/Gemfile.sequel-4.0.x

before_script:
  - mysql -e 'create database koine_repository'
  - psql -c 'create database koine_repository' -U postgres
